import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DitherBackground from "./DitherBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chatloom App",
  description: "Generated by create-chatloom",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&family=Inter:wght@400;500;700&display=swap" rel="stylesheet" />
      </head>
      <body style={{ background: 'transparent', position: 'relative', minHeight: '100vh', overflow: 'auto' }}>
        <DitherBackground />
        <div style={{ position: 'relative', zIndex: 1 }} className="min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
